apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-demo
  namespace: app-demo
spec:
  chart:
    spec:
      version: "6.1.0"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: app-demo.staging
          paths:
            - path: /
              pathType: ImplementationSpecific
