apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: app-demo
  namespace: app-demo
spec:
  interval: 5m
  type: "oci"
  url: oci://ghcr.io/bvanderlugt
  secretRef:
    name: ghcr-credentials
