apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: app-demo
  namespace: app-demo
spec:
  interval: 5m
  url: oci://ghcr.io/bvanderlugt/gitops-demo-app-app-demo
  type: oci
  secretRef:
    name: ghcr-credentials
