apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: app-demo
  namespace: app-demo
spec:
  interval: 5m
  type: "oci"
    #url: oci://ghcr.io/bvanderlugt/gitops-demo-app
  insecure: true  # for using local oci registry
  url: oci://localhost:5000/helm-charts
    #secretRef:
    #name: ghcr-credentials
