apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-demo
  namespace: app-demo
spec:
  chart:
    spec:
      version: ">=0.0.1"
  values:
    ingress:
      hosts:
        - host: app-demo.production
          paths:
            - path: /
              pathType: ImplementationSpecific
