name: Publish Helm Chart

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag the chart with (e.g. 1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  CHART_NAME: app-demo

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Update chart version
        run: |
          # Update the Chart.yaml version field
          sed -i "s/^version: .*/version: ${{ github.event.inputs.version }}/" helm-chart/Chart.yaml
          
          # Update the Chart.yaml appVersion field to match
          sed -i "s/^appVersion: .*/appVersion: \"${{ github.event.inputs.version }}\"/" helm-chart/Chart.yaml
          
          # Display the updated Chart.yaml
          cat helm-chart/Chart.yaml

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: |
          mkdir -p .cr-release-packages
          helm package helm-chart --destination .cr-release-packages

      - name: Push Helm chart
        run: |
          echo "Logging into Helm registry..."
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }}/${{ env.OWNER }} --username ${{ github.actor }} --password-stdin
          
          echo "Pushing chart to registry..."
          helm push .cr-release-packages/app-demo-${{ github.event.inputs.version }}.tgz oci://${{ env.REGISTRY }}/${{ env.OWNER }}
          
          echo "Chart published successfully!"